# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3ef8e132b9b3ef1333296dd22e8e5e676940dcf056e189e11a37c241e27edb0291454eb90217d3df79b62898ee52227bca39b494d6aff6f289944e2266a6cb04

test:
  secret_key_base: 7149e5b4c74c32f6dc5f381e5909647e69ae3b0c269096c95b82100c0bddada54795166f18b576d600b92f3b89a207074c84b7c269680e39db48552d8289d04f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
